export type ComplianceItem = { title: string; detail: string };
export type ComplianceProfile = { jurisdiction: string; statusLabel: string; summary: string; requiredStructure: string[]; checklist: ComplianceItem[]; documents: string[]; officialLinks: { label: string; href: string }[] };

const tamilNaduRules = "https://www.tnurbantree.tn.gov.in/sivagangai/wp-content/uploads/sites/38/2023/07/TNCDBR-2019.pdf";
const tamilNaduPortal = "https://www.tnurbantree.tn.gov.in/";

export function getComplianceProfile(state: string, buildingType: string): ComplianceProfile {
  if (state.toLowerCase() === "tamil nadu") {
    const highRiseNote = buildingType === "commercial" ? "For commercial or taller buildings, the approving authority may require additional drainage, recharge, and planning-permission details." : "For independent houses and apartments up to the applicable non-high-rise limits, the rules describe first-flush filtration with sump/source-well, recharge-well, or percolation-pit options.";
    return { jurisdiction: `Tamil Nadu · ${buildingType.replaceAll("_", " ")}`, statusLabel: "Confirm with municipality", summary: "Tamil Nadu Combined Development and Building Rules, 2019 require effective rainwater conservation measures and say the RWH structures should be shown in the plan submitted for planning permission.", requiredStructure: ["Show rooftop/campus rainwater-harvesting structures in the planning-permission plan.", "Provide rainwater pipes, first-flush plus pebble-sand or approved filter arrangements, and a safe overflow route.", "Select source-well, recharge-well, or percolation-pit arrangement based on site conditions and available space.", highRiseNote], checklist: [{ title: "RWH layout shown on plan", detail: "Mark roof catchments, downpipes, filters, storage, overflow, and recharge structures." }, { title: "First-flush and filtration included", detail: "Keep the first rainfall diversion and a maintainable filter chamber in the design." }, { title: "Overflow and stormwater route checked", detail: "Ensure excess water can discharge safely without dampness or nuisance flooding." }, { title: "Soil and recharge suitability checked", detail: "A qualified person should confirm soil absorption, slope, groundwater, and pit/well safety." }, { title: "Municipality / panchayat confirmation pending", detail: "Ask the relevant local authority which plan, permission, and completion documents apply." }], documents: ["Site plan showing the RWH layout and structures", "Roof drainage / downpipe schematic", "Property or approved-building plan available to the owner", "Installer design note with storage, filter, and recharge details", "Site photos and measurements for the authority or installer"], officialLinks: [{ label: "Tamil Nadu Combined Development and Building Rules, 2019 (PDF)", href: tamilNaduRules }, { label: "Tamil Nadu Urban Local Bodies portal", href: tamilNaduPortal }] };
  }
  return { jurisdiction: `${state} · local guidance not configured`, statusLabel: "Confirm with municipality", summary: "NeerPlan does not yet have a verified state-specific rule profile for this location. Treat this checklist as preparation guidance and confirm requirements with the local municipality, corporation, panchayat, or planning authority.", requiredStructure: ["Confirm whether rainwater harvesting is required for this property and building type.", "Ask the authority whether the RWH layout must appear in the planning or completion documents.", "Have a qualified installer verify filter, storage, overflow, and recharge arrangements for the site."], checklist: [{ title: "Local requirement checked", detail: "Record the authority, date, and guidance received." }, { title: "Plan and document requirements checked", detail: "Confirm which drawings, permissions, and completion documents are needed." }, { title: "Site and soil conditions checked", detail: "Confirm safe storage, drainage, and recharge feasibility with a qualified person." }], documents: ["Site plan and rooftop drainage sketch", "Installer design note", "Property or approved-building plan", "Site photos and measurements"], officialLinks: [{ label: "Find the relevant local authority", href: "https://www.india.gov.in/" }] };
}
