export const languages = [["en", "English"], ["ta", "தமிழ்"], ["hi", "हिन्दी"], ["te", "తెలుగు"], ["kn", "ಕನ್ನಡ"], ["ml", "മലയാളം"]] as const;
export type Language = (typeof languages)[number][0];
export const translations: Record<Language, Record<string, string>> = {
  en: { assessment: "Assessment", dashboard: "Dashboard", installer: "Installer portal", signIn: "Sign in", heroTitle: "Turn every rooftop into a water source.", heroText: "NeerPlan helps households and communities assess, plan, and act on rainwater harvesting.", freeAssessment: "FREE ASSESSMENT", calculate: "Calculate my potential →", save: "Save assessment", language: "Language", compliance: "Verified compliance guidance", guidance: "Guidance only — not legal approval." },
  ta: { assessment: "மதிப்பீடு", dashboard: "டாஷ்போர்டு", installer: "நிறுவுநர் தளம்", signIn: "உள்நுழை", heroTitle: "ஒவ்வொரு கூரையையும் நீர் ஆதாரமாக மாற்றுங்கள்.", heroText: "மழைநீர் சேகரிப்பை மதிப்பிடவும், திட்டமிடவும், செயல்படுத்தவும் NeerPlan உதவுகிறது.", freeAssessment: "இலவச மதிப்பீடு", calculate: "எனது திறனை கணக்கிடு →", save: "மதிப்பீட்டை சேமி", language: "மொழி", compliance: "சரிபார்க்கப்பட்ட இணக்க வழிகாட்டி", guidance: "வழிகாட்டுதல் மட்டுமே — சட்ட அனுமதி அல்ல." },
  hi: { assessment: "मूल्यांकन", dashboard: "डैशबोर्ड", installer: "इंस्टॉलर पोर्टल", signIn: "साइन इन", heroTitle: "हर छत को जल स्रोत में बदलें।", heroText: "NeerPlan वर्षा जल संचयन का आकलन, योजना और कार्यान्वयन में मदद करता है।", freeAssessment: "मुफ्त मूल्यांकन", calculate: "मेरी क्षमता की गणना करें →", save: "मूल्यांकन सहेजें", language: "भाषा", compliance: "सत्यापित अनुपालन मार्गदर्शन", guidance: "केवल मार्गदर्शन — कानूनी स्वीकृति नहीं।" },
  te: { assessment: "అంచనా", dashboard: "డాష్‌బోర్డ్", installer: "ఇన్‌స్టాలర్ పోర్టల్", signIn: "సైన్ ఇన్", heroTitle: "ప్రతి పైకప్పును నీటి వనరుగా మార్చండి.", heroText: "వర్షపు నీటి సంరక్షణను అంచనా వేయడానికి, ప్రణాళిక చేయడానికి NeerPlan సహాయపడుతుంది.", freeAssessment: "ఉచిత అంచనా", calculate: "నా సామర్థ్యాన్ని లెక్కించండి →", save: "అంచనాను సేవ్ చేయండి", language: "భాష", compliance: "ధృవీకరించిన అనుసరణ మార్గదర్శకం", guidance: "మార్గదర్శకం మాత్రమే — చట్టపరమైన అనుమతి కాదు." },
  kn: { assessment: "ಮೌಲ್ಯಮಾಪನ", dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", installer: "ಇನ್‌ಸ್ಟಾಲರ್ ಪೋರ್ಟಲ್", signIn: "ಸೈನ್ ಇನ್", heroTitle: "ಪ್ರತಿ ಮೇಲ್ಛಾವಣಿಯನ್ನು ನೀರಿನ ಮೂಲವನ್ನಾಗಿ ಮಾಡಿ.", heroText: "ಮಳೆನೀರು ಕೊಯ್ಲನ್ನು ಮೌಲ್ಯಮಾಪನ ಮಾಡಲು ಮತ್ತು ಯೋಜಿಸಲು NeerPlan ಸಹಾಯ ಮಾಡುತ್ತದೆ.", freeAssessment: "ಉಚಿತ ಮೌಲ್ಯಮಾಪನ", calculate: "ನನ್ನ ಸಾಮರ್ಥ್ಯ ಲೆಕ್ಕಿಸಿ →", save: "ಮೌಲ್ಯಮಾಪನ ಉಳಿಸಿ", language: "ಭಾಷೆ", compliance: "ಪರಿಶೀಲಿಸಿದ ಅನುಸರಣೆ ಮಾರ್ಗದರ್ಶನ", guidance: "ಮಾರ್ಗದರ್ಶನ ಮಾತ್ರ — ಕಾನೂನು ಅನುಮೋದನೆ ಅಲ್ಲ." },
  ml: { assessment: "വിലയിരുത്തൽ", dashboard: "ഡാഷ്ബോർഡ്", installer: "ഇൻസ്റ്റാളർ പോർട്ടൽ", signIn: "സൈൻ ഇൻ", heroTitle: "ഓരോ മേൽക്കൂരയും ജലസ്രോതസ്സാക്കാം.", heroText: "മഴവെള്ള സംഭരണം വിലയിരുത്താനും ആസൂത്രണം ചെയ്യാനും NeerPlan സഹായിക്കുന്നു.", freeAssessment: "സൗജന്യ വിലയിരുത്തൽ", calculate: "എന്റെ സാധ്യത കണക്കാക്കുക →", save: "വിലയിരുത്തൽ സംരക്ഷിക്കുക", language: "ഭാഷ", compliance: "പരിശോധിച്ച അനുസരണ മാർഗ്ഗനിർദ്ദേശം", guidance: "മാർഗ്ഗനിർദ്ദേശം മാത്രം — നിയമാനുമതി അല്ല." },
};
const extras: Record<Language, Record<string, string>> = {
  en: { nextStep: "NEXT STEP", installerTitle: "Talk to a local installer.", installerText: "Request a site survey to refine this estimate and plan the installation.", name: "Name", phone: "Phone number", requestSurvey: "Request a survey", sending: "Sending…", requestShared: "Thanks — your request has been shared with our installer network.", complianceTitle: "VERIFIED COMPLIANCE GUIDANCE", status: "Status", reviewed: "Guidance reviewed — municipality confirmation still pending", pending: "Confirm with municipality", markReviewed: "Mark guidance reviewed", keepPending: "Keep confirmation pending", required: "Required structure guidance", checklist: "Readiness checklist", documents: "Documents to prepare", officialLinks: "Official links", confirm: "Confirm the final requirements, drawings, and approvals with the relevant local authority before installation.", dashboardTitle: "YOUR DASHBOARD", saved: "Saved assessments", recent: "Your recent rooftop assessments.", emptyDashboard: "Save an assessment to keep its estimate and plan next steps.", newAssessment: "Start a new assessment →", report: "Open printable report", print: "Print or save as PDF", download: "Download text report", back: "Back to dashboard" },
  ta: { nextStep: "அடுத்த படி", installerTitle: "உள்ளூர் நிறுவுநருடன் பேசுங்கள்.", installerText: "இந்த மதிப்பீட்டை மேம்படுத்த தள ஆய்வு மற்றும் மேற்கோள் கோருங்கள்.", name: "பெயர்", phone: "தொலைபேசி எண்", requestSurvey: "ஆய்வைக் கோருங்கள்", sending: "அனுப்புகிறது…", requestShared: "உங்கள் கோரிக்கை நிறுவுநர் வலையமைப்பிற்கு பகிரப்பட்டது.", complianceTitle: "சரிபார்க்கப்பட்ட இணக்க வழிகாட்டி", status: "நிலை", reviewed: "வழிகாட்டி மதிப்பாய்வு செய்யப்பட்டது — நகராட்சி உறுதி நிலுவையில்", pending: "நகராட்சியுடன் உறுதி செய்யவும்", markReviewed: "மதிப்பாய்வு செய்ததாக குறிக்கவும்", keepPending: "உறுதியை நிலுவையில் வைக்கவும்", required: "தேவையான கட்டமைப்பு வழிகாட்டி", checklist: "தயார்நிலை சரிபார்ப்பு", documents: "தயார் செய்ய வேண்டிய ஆவணங்கள்", officialLinks: "அதிகாரப்பூர்வ இணைப்புகள்", confirm: "நிறுவுவதற்கு முன் உள்ளூர் அதிகாரியிடம் இறுதி தேவைகளை உறுதி செய்யவும்.", dashboardTitle: "உங்கள் டாஷ்போர்டு", saved: "சேமித்த மதிப்பீடுகள்", recent: "உங்கள் சமீபத்திய கூரை மதிப்பீடுகள்.", emptyDashboard: "மதிப்பீட்டை சேமித்து அடுத்த படிகளைத் திட்டமிடுங்கள்.", newAssessment: "புதிய மதிப்பீட்டைத் தொடங்கு →", report: "அச்சிடக்கூடிய அறிக்கையைத் திற", print: "அச்சிடு அல்லது PDF ஆக சேமி", download: "உரை அறிக்கையைப் பதிவிறக்கு", back: "டாஷ்போர்டுக்குத் திரும்பு" },
  hi: {}, te: {}, kn: {}, ml: {},
};
for (const language of Object.keys(translations) as Language[]) translations[language] = { ...extras.en, ...extras[language], ...translations[language] };
for (const language of Object.keys(translations) as Language[]) Object.assign(translations[language], { city: "City", state: "State / UT", roofArea: "Roof area (sq ft)", roofType: "Roof type", buildingType: "Building type", installationSpace: "Available installation space", rainfall: "Annual rainfall (mm)", people: "People using water", locationEstimate: "Location-based estimate", useEstimate: "Use city estimate", manualOverride: "Manual override available.", concrete: "Concrete terrace", metal: "Metal roof", tiles: "Tiled roof", independent: "Independent house", apartment: "Apartment / shared building", commercial: "Commercial building", limited: "Limited", moderate: "Moderate", ample: "Ample" });
