"use client";
import { useEffect } from "react";
import { useLanguage } from "@/components/language-provider";
const common = { "Draw your rooftop boundary.": "Draw your rooftop boundary.", Search: "Search", "Clear boundary": "Clear boundary", Normal: "Normal", Satellite: "Satellite", Terrain: "Terrain", "Roof area (sq ft)": "Roof area (sq ft)", "Roof type": "Roof type", "Building type": "Building type", "Available installation space": "Available installation space", "Annual rainfall (mm)": "Annual rainfall (mm)", "People using water": "People using water", "Use city estimate": "Use city estimate", "Location-based estimate": "Location-based estimate", "Calculate my potential →": "Calculate my potential →", "Save assessment": "Save assessment", "Annual collection": "Annual collection", "Suggested storage": "Suggested storage", "Annual savings": "Annual savings", "Expected payback": "Expected payback", "Use the layer switcher for Normal, Satellite, or Terrain views.": "Use the layer switcher for Normal, Satellite, or Terrain views." };
const map: Record<string, Record<string, string>> = {
  en: common,
  ta: { ...common, "Draw your rooftop boundary.": "உங்கள் கூரை எல்லையை வரையுங்கள்.", Search: "தேடு", "Clear boundary": "எல்லையை அழி", Normal: "இயல்பு", Satellite: "செயற்கைக்கோள்", Terrain: "நிலப்பரப்பு", "Roof area (sq ft)": "கூரை பரப்பளவு (சதுர அடி)", "Roof type": "கூரை வகை", "Building type": "கட்டிட வகை", "Available installation space": "கிடைக்கும் நிறுவல் இடம்", "Annual rainfall (mm)": "ஆண்டு மழையளவு (மிமீ)", "People using water": "நீரைப் பயன்படுத்துபவர்கள்", "Use city estimate": "நகர மதிப்பீட்டைப் பயன்படுத்து", "Calculate my potential →": "என் திறனை கணக்கிடு →", "Save assessment": "மதிப்பீட்டை சேமி" },
  hi: { ...common, "Draw your rooftop boundary.": "अपनी छत की सीमा बनाएं।", Search: "खोजें", "Clear boundary": "सीमा साफ करें", Normal: "सामान्य", Satellite: "उपग्रह", Terrain: "भूभाग", "Roof area (sq ft)": "छत का क्षेत्रफल (वर्ग फुट)", "Roof type": "छत का प्रकार", "Building type": "भवन का प्रकार", "Available installation space": "उपलब्ध स्थापना स्थान", "Annual rainfall (mm)": "वार्षिक वर्षा (मिमी)", "People using water": "पानी उपयोग करने वाले लोग", "Use city estimate": "शहर का अनुमान उपयोग करें", "Calculate my potential →": "मेरी क्षमता की गणना करें →", "Save assessment": "मूल्यांकन सहेजें" },
  te: { ...common, "Draw your rooftop boundary.": "మీ పైకప్పు సరిహద్దును గీయండి.", Search: "వెతుకు", "Clear boundary": "సరిహద్దు తొలగించు", Normal: "సాధారణం", Satellite: "ఉపగ్రహం", Terrain: "భూభాగం", "Roof area (sq ft)": "పైకప్పు విస్తీర్ణం (చ.అ.)", "Roof type": "పైకప్పు రకం", "Building type": "భవనం రకం", "Annual rainfall (mm)": "వార్షిక వర్షపాతం (మిమీ)", "People using water": "నీరు ఉపయోగించే వ్యక్తులు", "Use city estimate": "నగర అంచనాను ఉపయోగించండి", "Calculate my potential →": "నా సామర్థ్యాన్ని లెక్కించండి →", "Save assessment": "అంచనాను సేవ్ చేయండి" },
  kn: { ...common, "Draw your rooftop boundary.": "ನಿಮ್ಮ ಮೇಲ್ಛಾವಣಿ ಗಡಿಯನ್ನು ಬಿಡಿಸಿ.", Search: "ಹುಡುಕಿ", "Clear boundary": "ಗಡಿ ತೆರವುಗೊಳಿಸಿ", Normal: "ಸಾಮಾನ್ಯ", Satellite: "ಉಪಗ್ರಹ", Terrain: "ಭೂಪ್ರದೇಶ", "Roof area (sq ft)": "ಮೇಲ್ಛಾವಣಿ ವಿಸ್ತೀರ್ಣ (ಚದರ ಅಡಿ)", "Roof type": "ಮೇಲ್ಛಾವಣಿ ಪ್ರಕಾರ", "Building type": "ಕಟ್ಟಡ ಪ್ರಕಾರ", "Annual rainfall (mm)": "ವಾರ್ಷಿಕ ಮಳೆ (ಮಿಮೀ)", "People using water": "ನೀರು ಬಳಸುವ ಜನರು", "Use city estimate": "ನಗರ ಅಂದಾಜು ಬಳಸಿ", "Calculate my potential →": "ನನ್ನ ಸಾಮರ್ಥ್ಯ ಲೆಕ್ಕಿಸಿ →", "Save assessment": "ಮೌಲ್ಯಮಾಪನ ಉಳಿಸಿ" },
  ml: { ...common, "Draw your rooftop boundary.": "നിങ്ങളുടെ മേൽക്കൂരയുടെ അതിർത്തി വരയ്ക്കുക.", Search: "തിരയുക", "Clear boundary": "അതിർത്തി മായ്ക്കുക", Normal: "സാധാരണ", Satellite: "ഉപഗ്രഹം", Terrain: "ഭൂപ്രദേശം", "Roof area (sq ft)": "മേൽക്കൂര വിസ്തീർണ്ണം (ചതുരശ്ര അടി)", "Roof type": "മേൽക്കൂര തരം", "Building type": "കെട്ടിട തരം", "Annual rainfall (mm)": "വാർഷിക മഴ (മിമീ)", "People using water": "വെള്ളം ഉപയോഗിക്കുന്നവർ", "Use city estimate": "നഗര കണക്കുകൂട്ടൽ ഉപയോഗിക്കുക", "Calculate my potential →": "എന്റെ സാധ്യത കണക്കാക്കുക →", "Save assessment": "വിലയിരുത്തൽ സംരക്ഷിക്കുക" },
};
const originals = new WeakMap<Text, string>();
Object.assign(map.ta, { "Turn every rooftop into a water source.": "ஒவ்வொரு கூரையையும் நீர் ஆதாரமாக மாற்றுங்கள்.", "NeerPlan helps households and communities assess, plan, and act on rainwater harvesting.": "மழைநீர் சேகரிப்பை மதிப்பிடவும், திட்டமிடவும், செயல்படுத்தவும் NeerPlan உதவுகிறது.", "Plan with confidence.": "நம்பிக்கையுடன் திட்டமிடுங்கள்.", "Start a free, transparent rooftop assessment below.": "கீழே இலவச, வெளிப்படையான கூரை மதிப்பீட்டைத் தொடங்குங்கள்.", Assessment: "மதிப்பீடு", Dashboard: "டாஷ்போர்டு", "Installer portal": "நிறுவுநர் தளம்" });
Object.assign(map.hi, { "Turn every rooftop into a water source.": "हर छत को जल स्रोत में बदलें।", "NeerPlan helps households and communities assess, plan, and act on rainwater harvesting.": "NeerPlan वर्षा जल संचयन का आकलन और योजना बनाने में मदद करता है।", "Plan with confidence.": "विश्वास के साथ योजना बनाएं।", "Start a free, transparent rooftop assessment below.": "नीचे निःशुल्क पारदर्शी छत मूल्यांकन शुरू करें।", Assessment: "मूल्यांकन", Dashboard: "डैशबोर्ड", "Installer portal": "इंस्टॉलर पोर्टल" });
Object.assign(map.te, { "Turn every rooftop into a water source.": "ప్రతి పైకప్పును నీటి వనరుగా మార్చండి.", "Plan with confidence.": "నమ్మకంతో ప్రణాళిక చేయండి.", Assessment: "అంచనా", Dashboard: "డాష్‌బోర్డ్", "Installer portal": "ఇన్‌స్టాలర్ పోర్టల్" });
Object.assign(map.kn, { "Turn every rooftop into a water source.": "ಪ್ರತಿ ಮೇಲ್ಛಾವಣಿಯನ್ನು ನೀರಿನ ಮೂಲವನ್ನಾಗಿ ಮಾಡಿ.", "Plan with confidence.": "ವಿಶ್ವಾಸದಿಂದ ಯೋಜಿಸಿ.", Assessment: "ಮೌಲ್ಯಮಾಪನ", Dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", "Installer portal": "ಇನ್‌ಸ್ಟಾಲರ್ ಪೋರ್ಟಲ್" });
Object.assign(map.ml, { "Turn every rooftop into a water source.": "ഓരോ മേൽക്കൂരയും ജലസ്രോതസ്സാക്കാം.", "Plan with confidence.": "വിശ്വാസത്തോടെ ആസൂത്രണം ചെയ്യുക.", Assessment: "വിലയിരുത്തൽ", Dashboard: "ഡാഷ്ബോർഡ്", "Installer portal": "ഇൻസ്റ്റാളർ പോർട്ടൽ" });
export function LanguageDomTranslator() { const { language } = useLanguage(); useEffect(() => { const dictionary = map[language]; const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT); const nodes: Text[] = []; let node: Node | null; while ((node = walker.nextNode())) nodes.push(node as Text); for (const text of nodes) { const current = text.nodeValue ?? ""; if (!originals.has(text)) originals.set(text, current); const original = originals.get(text)!; const value = original.trim(); text.nodeValue = dictionary[value] ? original.replace(value, dictionary[value]) : original; } }, [language]); return null; }
