"use client";
import { useEffect, useState } from "react";

type Quote = { id: string; systemType: string; tankLitres: number | null; material: string; warrantyMonths: number; priceInr: number; installationDate: string | null };
export function QuoteComparison({ assessmentId }: { assessmentId: string }) {
  const [quotes, setQuotes] = useState<Quote[]>([]); const [requested, setRequested] = useState(0); const [message, setMessage] = useState(""); const [count, setCount] = useState("2");
  useEffect(() => { fetch(`/api/assessments/${assessmentId}/quotes`).then((r) => r.ok ? r.json() : null).then((d) => { if (d) { setQuotes(d.quotes); setRequested(d.requested); } }); }, [assessmentId]);
  async function requestQuotes() { setMessage(""); const response = await fetch(`/api/assessments/${assessmentId}/quotes`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ quoteCount: Number(count) }) }); const data = await response.json(); if (!response.ok) { setMessage(data.error ?? "Unable to request quotes."); return; } setRequested(data.requested); setMessage(`Your request for ${data.requested} quotes is active.`); }
  return <section className="quote-comparison"><p className="eyebrow">INSTALLER QUOTE COMPARISON</p><h3>Compare up to three quotes</h3><p>Ask for multiple options, then compare the system, warranty, price, and installation date.</p><div className="quote-request"><select value={count} onChange={(e) => setCount(e.target.value)}><option value="2">Request 2 quotes</option><option value="3">Request 3 quotes</option></select><button type="button" onClick={requestQuotes}>Request quotes</button></div>{message && <p className="form-message" role="status">{message}</p>}{requested > 0 && <p className="field-help">Requested {requested} quotes · {quotes.length} received so far.</p>}{quotes.length > 0 ? <div className="quote-grid">{quotes.map((quote) => <article key={quote.id}><h4 data-no-translate>{quote.systemType}</h4><dl><div><dt>Tank</dt><dd>{quote.tankLitres ? `${quote.tankLitres.toLocaleString("en-IN")} L` : "As surveyed"}</dd></div><div><dt>Material</dt><dd data-no-translate>{quote.material}</dd></div><div><dt>Warranty</dt><dd>{quote.warrantyMonths} months</dd></div><div><dt>Price</dt><dd>₹{quote.priceInr.toLocaleString("en-IN")}</dd></div><div><dt>Installation</dt><dd>{quote.installationDate ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium" }).format(new Date(quote.installationDate)) : "To be agreed"}</dd></div></dl></article>)}</div> : <p className="empty-state">No quotes received yet. Assigned installers can add their proposals here.</p>}</section>;
}
